### ISSUE TITLE
Receiver does not work

### ISSUE THREAD

**Issue by Ankurjain30** [safetysystemtechnology/android-shake-detector#2]
Followed ur steps as below.

1. complied with lib
2. added manifest permission and receiver
3. Created receiver class but no intent received on shake in nexus 5.

Did i miss something to mention in code!?

**Comment by netodevel** [comment]
you have declared the option `.background(true)` in ShakeOptions?

**Comment by Ankurjain30** [comment]
Let me share what i did, then guide.

My Receiver Class (Added .background in this as per advice, believing it is not the correct way)

public class ShakeReceiver extends BroadcastReceiver {
    @Override
    public void onReceive(Context context, Intent intent) {
        ShakeOptions shakeOptions = new ShakeOptions()
                .background(true)
                .shakeCount(2)
                .sensibility(2.0f)
                .interval(1000);


        if (null != intent && intent.getAction().equals("shake.detector")) {
            Popup.smallpopup("Shaken",context);
        }
    }
}

My Manifest
<receiver android:name=".ShakeReceiver">
            <intent-filter>
                <action android:name="shake.detector" />
            </intent-filter>
        </receiver>

There i no other class i created so far. Pls guide now.

**Comment by Ankurjain30** [comment]
it's done. I created one service instead of mainactivity and game over. thanks for wounderful coding.

**Comment by nehapraksh** [comment]
My ShakeReceiver is not working. I followed all the steps described in the documentation, but it does not work. Please help!

**Comment by netodevel** [comment]
@nehapraksh could you give me an example with code?

**Comment by nehapraksh** [comment]
Written below code at onCreate of  my MainActivity class:
  ShakeOptions options = new ShakeOptions()
                .background(true)
                .interval(1000)
                .shakeCount(2)
                .sensibility(2.0f);

//        this.shakeDetector = new ShakeDetector(options).start(this, new ShakeCallback() {
//            @Override
//            public void onShake() {
//  
//            }
//        });

        //IF YOU WANT JUST IN BACKGROUND
        this.shakeDetector = new ShakeDetector(options).start(this);

Below is my ShakeReceiver class:
public class ShakeReceiver extends BroadcastReceiver {
    @Override
    public void onReceive(Context context, Intent intent) {
        
        if (null != intent && intent.getAction().equals("shake.detector")) {
            Log.d("MyShakeReceiver", ">>>>>> my receiver <<<<<");
        }
    }
}

And this is the manifest code:
 <uses-feature android:name="android.hardware.sensor.accelerometer" android:required="true" />

<receiver android:name=".ShakeReceiver">
            <intent-filter>
                <action android:name="shake.detector" />
            </intent-filter>

**Comment by netodevel** [comment]
remove this and try again.
```
 //IF YOU WANT JUST IN BACKGROUND
this.shakeDetector = new ShakeDetector(options).start(this);
```

**Comment by nehapraksh** [comment]
I replaced the below line: 
this.shakeDetector = new ShakeDetector(options).start(this); 
with the code:
this.shakeDetector = new ShakeDetector(options).start(this, new ShakeCallback() {
 @override
 public void onShake() {

 }
 });

but nothing happened. :-(

**Comment by nehapraksh** [comment]
@Ankurjain30  Can you please help me with this? How did you resolve this issue?

**Comment by netodevel** [comment]
@nehapraksh put the permissions on the manifest?

**Comment by nehapraksh** [comment]
@NetoDevel  which permission?

**Comment by netodevel** [comment]
@nehapraksh Add in your `AndroidManifest`

`<uses-feature android:name="android.hardware.sensor.accelerometer" android:required="true" />
`

**Comment by nehapraksh** [comment]
Already did this.

**Comment by netodevel** [comment]
@nehapraksh can you upload to git so I can clone and see the problem?
