### ISSUE TITLE
Import error 

### ISSUE THREAD

**Issue by jamshaid120** [safetysystemtechnology/android-shake-detector#6]
I added the dependency in my Gradle file, and it ends up with 
`ERROR: Failed to resolve: com.github.safetysystemtechnology:android-shake-detector:v1.2
Show in Project Structure dialog
Affected Modules: app
`
My internet connection is working fine, but it still says that. Any solutions?

**Comment by netodevel** [comment]
try the latest version, please

https://github.com/safetysystemtechnology/android-shake-detector/releases

**Comment by jamshaid120** [comment]
> try the latest version, please
> 
> https://github.com/safetysystemtechnology/android-shake-detector/releases
It's throwing the error for v1.4 too.
ERROR: Failed to resolve: com.github.safetysystemtechnology:android-shake-detector:v1.4

**Comment by netodevel** [comment]
Okay, last question before further investigation:
Have you added the jit repository to your build.gradle?
```

repositories {
    ...
    maven { url 'https://jitpack.io' }
}
```

**Comment by jamshaid120** [comment]
> Okay, the last question before further investigation:
> Have you added the jit repository to your build.gradle?
> 
> ```
> 
> repositories {
>     ...
>     maven { url 'https://jitpack.io' }
> }
> ```

Sorry. I was missing that. I want to add some actions to onShake. where do I put that? It's not working in 
        
`shakeDetector.start(this, new ShakeCallback() {
              @Override
              public void onShake() {
                 Toast.makeText(getApplicationContext(), "locationDetails", Toast.LENGTH_SHORT).show();
                String msg_txt = "THis is a sammple sms";
                String phoneNo = "03036018110";
                 sendSMS(phoneNo,msg_txt);//no SMS is being sent

                Log.d("event", "onShake");//no output in logcat
                Toast.makeText(getApplicationContext(), "Jamshaid", Toast.LENGTH_LONG).show();//no toast is being displayed.
            }
        });
`

**Comment by netodevel** [comment]
see example:
https://github.com/safetysystemtechnology/android-shake-detector/tree/master/app

**Comment by jamshaid120** [comment]
got it working. I had to shake the phone harder than expected, thanks
